// Coffee Types
export const GET_COFFEESHOPS = "GET_COFFEESHOPS";
export const COFFEESHOPS_LOADING = "COFFEESHOPS_LOADING";
export const GET_COFFEESHOP_BY_ID = "GET_COFFEESHOP_BY_ID";

// Auth Types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERROR = "SET_ERROR";
